CREATE DATABASE `dubbo` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE dubbo;

CREATE TABLE USER(
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
 USER_NAME VARCHAR(64),
 PASSWORD VARCHAR(64),
	CREATE_BY VARCHAR(64),
 CREATE_TIME TIMESTAMP,
 MODIFY_BY VARCHAR(64),
 MODIFY_TIME TIMESTAMP,
 VERSION INT DEFAULT 0,
 REMOVED INT DEFAULT 0
)