server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dubbo?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    name: druid
    initialization-mode: never
  jpa:
    show-sql: true
    database: MYSQL
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

dubbo:
  application:
    name: boot-user-consumer
  registry:
    address: zookeeper://10.232.228.157:2181

  ## 如果即作为消费者又作为服务端，则下面的协议不需要配置，否则会出现问题
  #protocol:
    #name: dubbo
    #port: 20082